### ISSUE TITLE
定时脚本跑了十多个小时,报错啦

### ISSUE THREAD

**Issue by jonny77** [swoft-cloud/swoft#568] opened 2019-02-26 02:26 UTC
![image](https://user-images.githubusercontent.com/1962170/53382930-d01b7b00-39b0-11e9-8715-424becce3f0b.png)

Warning: Swoole\Table::set(): unable to allocate memory. in /Users/admin/Documents/www/myswoft/vendor/swoft/task/src/Crontab/Crontab.php on line 245

/**
 * 随机数生成
 * @return int
 */
function genRandom(){

    $key = '';
    $pattern='0123456789';
    for( $i=0; $i<6; $i++ ) {
        $key .= $pattern[mt_rand(0, 9)];
    }
    return $key;
}

**Comment by FFAIY** [comment] 2019-02-26 03:07
Duplicate of #535

**Comment by FFAIY** [comment] 2019-02-26 03:07
#535

**Comment by inhere** [comment] 2019-02-26 03:48
@jonny77 更新下 task 组件

**Closed** 2019-04-02 05:32 UTC
Labels: question
